#!/usr/bin/env bash
backupExtension='.bak'

if [[ $# -eq 0 ]]; then
	echo "usage: backup -f|--file <filename> -e|--ext|--extension <extension>"
	exit 0
fi

while (( "$#" )); do
	case "$1" in
		-f|--file)
			file=$2
			shift 2
		;;
		-e|--ext|--extension)
			backupExtension=$2
			shift 2
		;;
		-*|--*=) # unsupported flags
			echo "error: unsupported flag $1" >&2
			exit 1
		;;
		*)
			echo "usage: backup -f|--file <filename> -e|--ext|--extension <extension>"
			exit 1
		;;
	esac
done

if [ ! -f $file ]; then
	echo "error: file $file not found" >&2
	exit 1
fi

if [[ ! $backupExtension == .* ]]; then
	backupExtension=".$backupExtension"
fi

cp $file "$file$backupExtension"
