#!/usr/bin/env bash
# `depth` takes two arguments: a root dir and a relative dir. It
# returns the distance the relative dir is away from the root dir.

# Counts number of directories deep from root a directory is.
function num_dirs {
	tr -dc "/" <<< $1 | wc -c
}

root_dirs=`num_dirs $1`
rel_dirs=`num_dirs $2`

expr $rel_dirs - $root_dirs
