#!/bin/zsh
# TODO: Change shebang to bash and add error note if it's an invalid version.
# TODO: Have the script return a negative number if the file appears above
#       the specified path.
tr -dc "/" <<< "${$(pwd)#"$1"}" | wc -c
