#!/bin/bash
# From: https://www.youtube.com/watch?v=NYGI5xh4Llc
# Make OSX compatible (after installing coreutils)
if [[ `uname` == 'Darwin' ]]; then
	shuf=gshuf
else
	shuf=shuf
fi

w3m -cols 999999 -dump http://en.wikipedia.org/wiki/$(date +%B_%d) \
	| sed -n '/Events/,/Births/ p' \
	| sed -n 's/^.*• //p' \
	| eval $shuf -n 1
