#!/usr/bin/env bash
# Creates a note file with boilerplate code inside.
# Note: This script assumes you have a NOTES_HOME variable that points to the
#       root directory of your notes.
# TODO: Don't append to file if it already exists. Throw error instead.
function pathToNotesHome {
	for (( i=1; i<=$(depth $NOTES_HOME `pwd`); i++ )); 
		do echo -n ../; 
	done
}

echo "<link rel='stylesheet' href='$(pathToNotesHome)shared/style.css'>" >> $1
echo >> $1
echo "<a href='$(pathToNotesHome)index.html'>Return to homepage.</a>" >> $1

