#!/bin/sh
#/ netdev: List available network devices
#/
#/ Options:
#/     -e|--enabled	Only list enabled devices
#/
#/ Usage: netdev [-e|--enabled]
enabled=''
for i in "$@"
do
case $i in
	-e|--enabled)
	enabled='.*state UP.*'
	shift
	;;
	-h|--help)
	grep ^\#\/ < "$0" | cut -c4-
	exit 1
	;;
	*)
	echo "Unknown option: $1"
	exit 2
	;;
esac
done

ip link | awk -v enabled="$enabled" '/^[0-9]+\:'"$enabled"'/ { print substr($2, 1, length($2) - 1) }'

