#!/bin/sh
#/ remote: Opens remote git repository in GitHub
#/
#/ Description:
#/   If no file is specified, then the repository's main page is opened.
#/
#/ Usage:
#/   remote [files]
set -e

open=$(command -v open || command -v xdg-open)
branch="$(git branch --show-current)"
for i in "$@"; do
    case $i in
        -h|--help)
            grep ^\#\/ < "$0" | cut -c4-
            exit 1
			;;
		-b|--branch)
			branch="$2"
			shift; shift
			;;
    esac
done

git ls-remote --heads --exit-code origin $branch || {
	default_branch=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
	echo "WARN: Branch '$branch' was not found on the origin repo, defaulting to $default_branch"
	branch=$default_branch
}

remote=$(git remote -v | grep fetch | awk '{ print $2 }')
case $remote in
    https://*)
        ;;
    git@*)
        remote=$(echo "$remote" |\
            awk 'BEGIN { FS = "[@:.]" } ; { print "https://"$2"."$3"/"$4 }')
        ;;
    *)
        echo "Unknown remote format" >&2
        exit 1
        ;;
esac

[ "$#" -lt 1 ] && {
    $open "$remote"
    exit
}

for file in "$@"; do
    $open "$remote/blob/$(git branch --show-current)/$file"
done
