#!/bin/sh
#/ remote: Opens remote git repository in GitHub
#/
#/ Description:
#/   If no file is specified, then the repository's main page is opened.
#/
#/ Usage:
#/   remote [file]
set -e

open=$(command -v open || command -v xdg-open)

for i in "$@"; do
	case $i in
		-h|--help)
			grep ^\#\/ < "$0" | cut -c4-
			exit 1
		;;
		*)
			echo "Opening file on remote is currently unsupported" >&2
			exit 1
		;;
	esac
done

remote=$(git remote -v | grep fetch | awk '{ print $2 }')
case $remote in
	https://*)
		$open "$remote"
		;;
	git@*)
		$open "$(echo "$remote" |\
			awk 'BEGIN { FS = "[@:.]" } ; { print "https://"$2"."$3"/"$4 }')"
		;;
	*)
		echo "Unknown remote format" >&2
		exit 1
		;;
esac
